version: '3'

#
# Connect to Elrond testnet, bind RPC port to 127.0.0.1:9999
#1.1.65.3
services:
  # https://docs.elrond.com/validators/testnet/use-docker-testnet/
  # https://hub.docker.com/r/elrondnetwork/elrond-go-node-testnet
  elrond:
    image: elrondnetwork/elrond-go-node-testnet:T1.1.65.3
    restart: always
    container_name: elrond
    network_mode: host
    command: --port 37373 --rest-api-interface 127.0.0.1:9999
    volumes:
      - ./validator.pem:/go/elrond-go/cmd/node/config/validatorKey.pem

